### ISSUE TITLE
chruby-exec seems to be broken

### ISSUE THREAD

**Issue by dalizard** [JeanMertz/chruby-fish#10]
I am running OSX 10.9.3, along with the following:

``` bash
~ $ chruby --version
chruby: 0.3.8
chruby-fish: 0.6.0
~ $ fish --version
fish, version 2.1.0
~ $
```

However, when trying to execute `chruby-exec`, I get the following error:

``` bash
~ $ chruby
   jruby-1.7.12
 * ruby-2.1.2
~ $ chruby-exec jruby-1.7.12 -- gem env
fish: Expected a command name, got token of type 'Run job in background'. Did you mean 'COMMAND; and COMMAND'? See the help section for the 'and' builtin command by typing 'help and'.
Standard input: chruby jruby-1.7.12 && gem env
                                     ^
~ $
```

Any ideas?

**Comment by JeanMertz** [comment]
I've been doing some testing, and have a semi-working prototype up in the [`chruby-exec`](https://github.com/JeanMertz/chruby-fish/tree/chruby-exec) branch. Some scenarios worked, others didn't, and I'm not too fond of the hacky solution, but we'll see where this ends up.

See https://github.com/JeanMertz/chruby-fish/commit/41f0e8518639a2b4fe9fab0e5fc712b294ff4502 for the implementation itself.

**Comment by JeanMertz** [comment]
I've never really had a need for `chruby-exec` in the last year or more, so I'm not going to try and fix this at this point in time, but PRs are always welcome.

**Comment by der-flo** [comment]
I'm also very interested in a solution.
