### ISSUE TITLE
"path component may not be valid" warning

### ISSUE THREAD

**Issue by jc00ke** [JeanMertz/chruby-fish#14]
```
$> cd ~/projects/foo/
set: Warning: path component /home/jesse/.rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/bin may not be valid in PATH.
set: No such file or directory
$> cat .ruby-version
2.1.5
$> chruby --version
chruby: 0.3.9
chruby-fish: 0.6.0
```

`chruby-fish` is actuall `HEAD` as of e8f28035e7

Ideas on how to suppress the warning? There's definitely no `bin/` in that `path` above.

**Comment by britishtea** [comment]
This is the same issue as #11 and #8. The suggested workaround is described [here](https://github.com/JeanMertz/chruby-fish/issues/8#issuecomment-43450618).

**Comment by jc00ke** [comment]
Thanks @britishtea, I ended up creating the missing directories. Since multiple people reported this, maybe it's worth mentioning in the README? I'll open a PR for that, but I understand if it won't be merged.
