### ISSUE TITLE
wishlist: support for gem_home

### ISSUE THREAD

**Issue by memoht** [JeanMertz/chruby-fish#16]
I am trying out fish shell for the first time and was so happy to run across your project. I use chruby, and ruby-install. I also use [gem_home](https://github.com/postmodern/gem_home) which is currently not supported. In a perfect world, @postmodern would add fish support to his projects. Fish shell seems like a nice alternative to zsh. Thanks again for creating this project.

**Comment by edc** [comment]
Checkout Bass: https://github.com/edc/bass

**Comment by JeanMertz** [comment]
I haven't had a real use for `gem_home` yet, but @edc's bass might help you out :+1:
