### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by nwjsmith** [JeanMertz/chruby-fish#28]
It'd be great if a release could go out that contains https://github.com/JeanMertz/chruby-fish/commit/76ff28a9950f076a32e7cb1017833af12d01037c

chruby-fish is great, thanks!

**Comment by JeanMertz** [comment]
@nwjsmith I just released a new version that includes the linked commit.

Let me know if it works for you 👍

**Comment by nwjsmith** [comment]
Thanks!
