### ISSUE TITLE
chruby-fish executing .bash_profile when changing ruby

### ISSUE THREAD

**Issue by espen** [JeanMertz/chruby-fish#32]
After [enabling](https://github.com/JeanMertz/chruby-fish#configuration) chruby-fish .bash_profile is executed for each ruby load. Is this intended behaviour?

I am not sourcing .bash_profile in my config.fish so it is only loaded when chruby-fish is changing rubies.

I would like to keep my . bash_profile for bash and not load this file when changing rubies in fish.

**Comment by JeanMertz** [comment]
Thank you for reporting this @espen. Apologies that it took me almost a year to respond.

I believe this was changed in https://github.com/JeanMertz/chruby-fish/commit/52bb9f4e15787387dd5ae28da551e186dfa68cd7#diff-808253f938d9786df749f46b6147ad2dR46.

I don't think we can easily change this without it being a breaking change, and without requiring some shuffling of existing code.

Feel free to open a PR that fixes this _and_ passes the current tests (provided you still use shrubby, and have a need for this). I'm closing this, as I don't expect to be working on this for the foreseeable future.
