### ISSUE TITLE
test suite no longer working on latest macOS releases

### ISSUE THREAD

**Issue by JeanMertz** [JeanMertz/chruby-fish#36]
It looks like RVM is no longer updating their binaries for newer OS versions:

```shell
chruby-fish ❯ make test

./test/setup
>>> Downloading https://rvm.io/binaries/osx/10.13/x86_64/ruby-2.2.5.tar.bz2 ...
--2018-09-15 10:23:47--  https://rvm.io/binaries/osx/10.13/x86_64/ruby-2.2.5.tar.bz2
Resolving rvm.io (rvm.io)... 151.101.130.49, 151.101.194.49, 151.101.2.49, ...
Connecting to rvm.io (rvm.io)|151.101.130.49|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-09-15 10:23:47 ERROR 404: Not Found.

!!! Download failed
make: *** [test/opt/rubies] Error 255
```

The CI still works, as it uses an older version of macOS. Unfortunately, I don't have the time to investigate and solve this issue. If anyone wants to tackle this issue, I'm willing to help them.

**Comment by heydonovan** [comment]
The 10.12 binary exists, do we want to hardcode it until RVM resumes building binaries?

https://rvm.io/binaries/osx/10.12/x86_64/ruby-2.2.5.tar.bz2

**Comment by JeanMertz** [comment]
@heydonovan sorry for getting back to you so late, it looks like I had my GitHub notifications misconfigured 😞.

It's been a while, but if you want to tackle this, feel free to do so! (and if you need help, feel free to ask).
